[package]
name = "timer_functional"
version = "0.1.0"
authors = ["Zahash <zahash.z@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
gloo.workspace = true
js-sys.workspace = true
yew = { path = "../../packages/yew", features = ["csr"] }
