[package]
name = "webgl"
version = "0.1.0"
authors = ["MikloÃÅs Tusz <mdtusz@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"
yew = { path = "../../packages/yew", features = ["csr"] }

[dependencies.web-sys]
version = "0.3"
features = [
  'HtmlCanvasElement',
  'WebGlBuffer',
  'WebGlProgram',
  'WebGlRenderingContext',
  'WebGlShader',
  'WebGlUniformLocation',
]
