[package]
name = "webgl"
version = "0.1.0"
authors = ["MikloÃÅs Tusz <mdtusz@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-sys = "0.3"
yew = { path = "../../yew", features = ["web_sys"] }
wasm-bindgen = "0.2"
web-sys = {version = "0.3", features = [
  'HtmlCanvasElement', 'WebGlBuffer', 'WebGlProgram', 'WebGlRenderingContext',
  'WebGlShader', 'WebGlUniformLocation',
]}
