[package]
name = "webgl"
version = "0.1.0"
authors = ["MikloÃÅs Tusz <mdtusz@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
js-sys.workspace = true
wasm-bindgen.workspace = true
yew = { path = "../../packages/yew", features = ["csr"] }

[dependencies.web-sys]
workspace = true
features = [
  'HtmlCanvasElement',
  'WebGlBuffer',
  'WebGlProgram',
  'WebGlRenderingContext',
  'WebGlShader',
  'WebGlUniformLocation',
]
