[package]
name = "minimal"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
edition = "2018"

[dependencies]
yew = { path = "../../yew" }
yew-config = { path = "../../yew-config" }

