[package]
name = "js-framework-benchmark-yew"
version = "1.0.0"
authors = ["Isamu Mogi <isamu@leafytree.jp>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = { version = "0.8.5", features = ["small_rng"] }
getrandom = { version = "0.2.8", features = ["js"] }
wasm-bindgen = "0.2.83"
web-sys = { version = "0.3.60", features = ["Window"]}
yew = { version = "0.20.0", features = ["csr"], path = "../../packages/yew" }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-O4']
