[package]
name = "portals"
version = "0.1.0"
authors = ["Martin Molzer <worldsbegin@gmx.de>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
yew = { path = "../../packages/yew" }
gloo-utils = "0.1"
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3"
features = [
    "Document",
    "Element",
    "Node",
    "HtmlHeadElement",
    "ShadowRoot",
    "ShadowRootInit",
    "ShadowRootMode",
]
