[package]
name = "portals"
version = "0.1.0"
authors = ["Martin Molzer <worldsbegin@gmx.de>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
yew = { path = "../../packages/yew", features = ["csr"] }
gloo.workspace = true
wasm-bindgen.workspace = true

[dependencies.web-sys]
workspace = true
features = [
    "Document",
    "Element",
    "Node",
    "HtmlHeadElement",
    "ShadowRoot",
    "ShadowRootInit",
    "ShadowRootMode",
]
