[package]
name = "inner_html"
version = "0.1.0"
authors = ["Garrett Berg <vitiral@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
yew = { path = "../../packages/yew" }
gloo-utils = "0.1"

[dependencies.web-sys]
version = "0.3"
features = ["console", "Document", "Element", "Node", "Window"]
