[package]
name = "inner_html"
version = "0.1.0"
authors = ["Garrett Berg <vitiral@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
yew = { path = "../../packages/yew", features = ["csr"] }
gloo.workspace = true

[dependencies.web-sys]
workspace = true
features = ["console", "Document", "Element", "Node", "Window"]
