[package]
name = "npm_and_rest"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
serde = "1"
serde_derive = "1"
stdweb = "0.4.20"
yew = { path = "../.." }
