[package]
name = "todomvc"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
strum.workspace = true
strum_macros.workspace = true
serde.workspace = true
serde_derive = "1"
yew = { path = "../../packages/yew", features = ["csr"] }
gloo.workspace = true

[dependencies.web-sys]
workspace = true
features = [
	"HtmlInputElement",
]
