[package]
name = "webgl"
version = "0.1.0"
authors = ["MikloÃÅs Tusz <mdtusz@gmail.com>"]
edition = "2018"

[dependencies]
stdweb = "0.4.20"
webgl_stdweb = {version = "0.3.0", optional = true}
yew-stdweb = { path = "../.." }

# Used to fix CI (most projects won't need this)
[target.'cfg(any(not(target_arch = "wasm32"), target_os="wasi", cargo_web))'.dependencies]
webgl_stdweb = "0.3.0"
