[package]
name = "yew-router"
version = "0.16.0"
authors = ["Hamza <muhammadhamza1311@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["web", "yew", "router"]
categories = ["gui", "web-programming"]
description = "A router implementation for the Yew framework"
repository = "https://github.com/yewstack/yew"
rust-version = "1.56.0"

[features]
wasm_test = []

[dependencies]
yew = { version = "0.19.3", path = "../yew", default-features= false }
yew-router-macro = { version = "0.16.0", path = "../yew-router-macro" }

wasm-bindgen = "0.2"
js-sys = "0.3"
gloo = { version = "0.6", features = ["futures"] }
route-recognizer = "0.3"
serde = "1"

[dependencies.web-sys]
version = "0.3"
features = [
    "Document",
    "HtmlBaseElement",
    "Window",
]

[dev-dependencies]
wasm-bindgen-test = "0.3"
serde = { version = "1", features = ["derive"] }

[dev-dependencies.web-sys]
version = "0.3"
features = [
    "HtmlHeadElement",
]
