[package]
name = "yew-router"
version = "0.15.0"
authors = ["Hamza <muhammadhamza1311@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["web", "yew", "router"]
categories = ["gui", "web-programming"]
description = "A router implementation for the Yew framework"
repository = "https://github.com/yewstack/yew"

[features]
wasm_test = []

[dependencies]
yew = { path = "../yew", default-features= false }
yew-router-macro = { path = "../yew-router-macro" }
gloo-utils = "0.1"

wasm-bindgen = "0.2"
js-sys = "0.3"
gloo = { version = "0.4", features = ["futures"] }
route-recognizer = "0.3"
serde = "1"
serde_urlencoded = "0.7"
serde-wasm-bindgen = "0.3.1"
thiserror = "1.0.30"

[dependencies.web-sys]
version = "0.3"
features = [
    "Attr",
    "Document",
    "History",
    "HtmlBaseElement",
    "Event",
    "NamedNodeMap",
    "Url",
    "UrlSearchParams",
    "Window",
]

[dev-dependencies]
wasm-bindgen-test = "0.3"
serde = { version = "1", features = ["derive"] }

[dev-dependencies.web-sys]
version = "0.3"
features = [
    "HtmlHeadElement",
]
