[package]
name = "yew-router"
version = "0.19.0"
authors = ["Hamza <muhammadhamza1311@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["web", "yew", "router"]
categories = ["gui", "web-programming"]
description = "A router implementation for the Yew framework"
repository = "https://github.com/yewstack/yew"
rust-version = "1.84.0"

[dependencies]
yew = { version = "0.22.1", path = "../yew", default-features= false }
yew-router-macro = { version = "0.19.0", path = "../yew-router-macro" }

wasm-bindgen.workspace = true
js-sys.workspace = true
gloo = { workspace = true, features = ["futures"] }
route-recognizer = "0.3"
serde.workspace = true
serde_urlencoded = "0.7.1"
tracing = "0.1.44"
urlencoding = "2.1.3"

[dependencies.web-sys]
workspace = true
features = [
    "Document",
    "HtmlBaseElement",
    "Window",
]

[dev-dependencies]
wasm-bindgen-test = "0.3"
serde = { workspace = true, features = ["derive"] }
yew = { version = "0.22.1", path = "../yew", features = ["csr"] }

[dev-dependencies.web-sys]
workspace = true
features = [
    "HtmlHeadElement",
]

[lints]
workspace = true
