[package]
name = "timer"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
yew = { path = "../../packages/yew" }
js-sys = "0.3"
gloo = "0.6"
wasm-bindgen = "0.2"
