[package]
name = "timer"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
yew = { path = "../../packages/yew", features = ["csr"] }
js-sys.workspace = true
gloo.workspace = true
wasm-bindgen.workspace = true
