branches:
  only:
    - staging
    - trying
    - master

dist: trusty
language: rust
sudo: false
addons:
  firefox: latest

cache: cargo
before_cache:
  - ./ci/clear_cache.sh

rust:
  - 1.42.0 # min supported
  - stable
  - beta

services:
  - docker

matrix:
  allow_failures:
    - rust: beta
  fast_finish: true

before_install:
  - docker run -d -p 8000:80 kennethreitz/httpbin@sha256:599fe5e5073102dbb0ee3dbb65f049dab44fa9fc251f6835c9990f8fb196a72b

install:
  - nvm install 9
  - rustup component add rustfmt
  - rustup component add clippy
  - rustup install stable
  - rustup target add wasm32-unknown-unknown
  - cargo +stable install wasm-pack
  - ./ci/install_cargo_web.sh

script:
  - ./ci/run_stable_checks.sh
  - HTTPBIN_URL="http://localhost:8000" ./ci/run_tests.sh
