branches:
  only:
    - staging
    - trying
    - master

language: rust

dist: trusty
sudo: false
addons:
  chrome: stable

cache:
  timeout: 1000
  directories:
    - $HOME/.cargo
    - $HOME/.nvm
    - $HOME/.rustup
    - $HOME/.local/share/cargo-web/emscripten

rust:
  - 1.35.0 # min supported
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

install:
  - nvm install 9
  - rustup component add rustfmt
  - rustup target add wasm32-unknown-unknown
  - cargo install cargo-update
  - cargo install-update-config --version =0.2.50 wasm-bindgen-cli
  - cargo install-update wasm-bindgen-cli
  - curl --retry 5 -LO https://chromedriver.storage.googleapis.com/2.41/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - ./ci/install_cargo_web.sh

script:
  - cargo fmt --all -- --check
  - CHROMEDRIVER=$(pwd)/chromedriver ./ci/run_tests.sh
