branches:
  only:
    - staging
    - trying
    - master

dist: trusty
language: rust
sudo: false
addons:
  chrome: stable

cache: cargo
before_cache:
  - ./ci/clear_cache.sh

rust:
  - 1.39.0 # min supported
  - stable
  - beta

matrix:
  allow_failures:
    - rust: beta
  fast_finish: true

install:
  - nvm install 9
  - rustup component add rustfmt
  - rustup component add clippy
  - rustup target add wasm32-unknown-unknown
  - cargo install cargo-update || true
  - cargo install-update-config --version =0.2.58 wasm-bindgen-cli
  - cargo install-update --allow-no-update wasm-bindgen-cli
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl --retry 5 -LO "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - ./ci/install_cargo_web.sh

script:
  - ./ci/run_checks.sh
  - CHROMEDRIVER=$(pwd)/chromedriver ./ci/run_tests.sh
  - CHROMEDRIVER=$(pwd)/chromedriver ./ci/check_examples.sh
