[workspace]
members = [
  "packages/yew",
  "packages/yew-macro",
  "packages/yew-validation",
  "packages/yew-agent",

  # Router
  "packages/yew-router",
  "packages/yew-router-macro",

  # Examples
  "examples/boids",
  "examples/counter",
  "examples/crm",
  "examples/dyn_create_destroy_apps",
  "examples/file_upload",
  "examples/function_todomvc",
  "examples/futures",
  "examples/game_of_life",
  "examples/inner_html",
  "examples/js_callback",
  "examples/keyed_list",
  "examples/mount_point",
  "examples/multi_thread",
  "examples/nested_list",
  "examples/node_refs",
  "examples/pub_sub",
  "examples/router",
  "examples/store",
  "examples/timer",
  "examples/todomvc",
  "examples/two_apps",
  "examples/webgl",

  # Release tools
  "packages/changelog",
]
exclude = [
  "packages/website-test",
]
