[workspace]
members = [
  "yew",
  "yew-components",
  "yew-functional",
  "yew-macro",
  "yew-validation",

  # Router
  "yew-router",
  "yew-router-macro",
  "yew-router-route-parser",
  "yew-router/examples/minimal",
  "yew-router/examples/router_component",
  "yew-router/examples/switch",

  # Utilities
  "yewtil",
  "yewtil-macro",
  "yewtil/examples/pure_component",
  # "yewtil/examples/dsl",
  "yewtil/examples/lrc",
  "yewtil/examples/history",
  "yewtil/examples/mrc_irc",
  "yewtil/examples/effect",
  "yewtil/examples/fetch",
  "yewtil/examples/futures",
  "yewtil/examples/function_component",

  # dsl
  "yew-dsl",

  # Examples
  "examples/counter",
  "examples/crm",
  "examples/custom_components",
  "examples/dashboard",
  "examples/file_upload",
  "examples/fragments",
  "examples/futures_wp",
  "examples/game_of_life",
  "examples/inner_html",
  "examples/js_callback",
  "examples/large_table",
  "examples/minimal",
  "examples/minimal_wp",
  "examples/mount_point",
  "examples/multi_thread",
  "examples/nested_list",
  "examples/node_refs",
  "examples/npm_and_rest",
  "examples/pub_sub",
  "examples/store",
  "examples/textarea",
  "examples/timer",
  "examples/todomvc",
  "examples/two_apps",
  "examples/webgl",
]
