[workspace]
members = [
  # Packages
  "packages/yew",
  "packages/yew-macro",
  "packages/yew-agent",
  "packages/yew-router",
  "packages/yew-router-macro",

  # Examples
  "examples/boids",
  "examples/counter",
  "examples/dyn_create_destroy_apps",
  "examples/file_upload",
  "examples/function_todomvc",
  "examples/futures",
  "examples/game_of_life",
  "examples/inner_html",
  "examples/js_callback",
  "examples/keyed_list",
  "examples/mount_point",
  "examples/multi_thread",
  "examples/nested_list",
  "examples/node_refs",
  "examples/password_strength",
  "examples/portals",
  "examples/pub_sub",
  "examples/router",
  "examples/store",
  "examples/timer",
  "examples/todomvc",
  "examples/two_apps",
  "examples/webgl",
  "examples/web_worker_fib",

  # Tools
  "tools/changelog",
  "tools/js-framework-benchmark/results_diff",
  "tools/js-framework-benchmark/frameworks/keyed/wasm-bindgen",
  "tools/js-framework-benchmark/frameworks/keyed/yew",
  "tools/js-framework-benchmark/frameworks/keyed/yew-baseline",
]
exclude = [
  # Tools
  "tools/website-test",
]
