[workspace]
members = [
  "yew",
  "yew-functional",
  "yew-macro",
  "yew-router",
  "yew-router-macro",
  "yew-router-route-parser",

  # Examples
  "examples/counter",
  "examples/crm",
  "examples/custom_components",
  "examples/dashboard",
  "examples/file_upload",
  "examples/fragments",
  "examples/futures",
  "examples/game_of_life",
  "examples/inner_html",
  "examples/js_callback",
  "examples/large_table",
  "examples/minimal",
  "examples/mount_point",
  "examples/multi_thread",
  "examples/nested_list",
  "examples/node_refs",
  "examples/npm_and_rest",
  "examples/pub_sub",
  "examples/server",
  "examples/textarea",
  "examples/timer",
  "examples/todomvc",
  "examples/two_apps",
  "examples/webgl",
]
