[workspace]
members = [
  "yew",
  "yew-components",
  "yew-macro",
  "yew-validation",

  # Router
  "yew-router",
  "yew-router-macro",
  "yew-router-route-parser",

  # Function components
  "yew-function-components",
  "yew-function-components-macro",

  # Utilities
  "yewtil",
  "yewtil-macro",

  # dsl
  "yew-dsl",

  # Examples
  "examples/boids",
  "examples/counter",
  "examples/crm",
  "examples/dashboard",
  "examples/file_upload",
  "examples/futures",
  "examples/game_of_life",
  "examples/inner_html",
  "examples/js_callback",
  "examples/keyed_list",
  "examples/mount_point",
  "examples/multi_thread",
  "examples/nested_list",
  "examples/node_refs",
  "examples/pub_sub",
  "examples/router",
  "examples/store",
  "examples/timer",
  "examples/todomvc",
  "examples/two_apps",
  "examples/webgl",
]
