[workspace]
members = [
  "packages/yew",
  "packages/yew-components",
  "packages/yew-macro",
  "packages/yew-services",
  "packages/yew-validation",

  # Router
  "packages/yew-router",
  "packages/yew-router-macro",

  # Function components
  "packages/yew-functional",
  "packages/yew-functional-macro",

  # Utilities
  "packages/yewtil",
  "packages/yewtil-macro",

  # Examples
  "examples/boids",
  "examples/counter",
  "examples/crm",
  "examples/dashboard",
  "examples/dyn_create_destroy_apps",
  "examples/file_upload",
  "examples/futures",
  "examples/game_of_life",
  "examples/inner_html",
  "examples/js_callback",
  "examples/keyed_list",
  "examples/mount_point",
  "examples/multi_thread",
  "examples/nested_list",
  "examples/node_refs",
  "examples/pub_sub",
  "examples/router",
  "examples/store",
  "examples/timer",
  "examples/todomvc",
  "examples/two_apps",
  "examples/webgl",

  # Release tools
  "packages/changelog",
]
