[package]
name = "yew-link"
version = "0.1.0"
edition = "2021"
rust-version = "1.84.0"
description = "Server-client state linking for Yew SSR"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { path = "../yew" }
yew-link-macro = { path = "../yew-link-macro" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
log = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
gloo-net = { version = "0.6", features = ["http"] }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true, features = ["Document", "Element", "HtmlElement", "HtmlScriptElement", "Window"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
axum = { workspace = true, optional = true }
tokio = { workspace = true, optional = true }

[features]
default = []
ssr = ["yew/ssr"]
hydration = ["yew/hydration"]
axum = ["dep:axum", "dep:tokio"]

[lints]
workspace = true
