[package]
name = "webgl_web_sys"
version = "0.1.0"
authors = ["MikloÃÅs Tusz <mdtusz@gmail.com>"]
edition = "2018"

[dependencies]
js-sys = "0.3"
yew = { path = "../../..", features = ["web_sys"] }
wasm-bindgen = "0.2"
web-sys = {version = "0.3", features = [
  'HtmlCanvasElement', 'WebGlBuffer', 'WebGlProgram', 'WebGlRenderingContext',
  'WebGlShader', 'WebGlUniformLocation',
]}
