[package]
name = "textarea"
version = "0.1.0"
authors = ["Andrew Straw <strawman@astraw.com>"]
edition = "2018"

[dependencies]
yew = { path = "../.." }

[features]
std_web = ["yew/std_web"]
web_sys = ["yew/web_sys"]
