[package]
name = "communication_parent_to_child"
version = "0.0.1"
authors = ["Marcel Ibes <mibes@mibesco.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
yew = { path = "../../packages/yew", features = ["csr"] }
