[package]
name = "function_memory_game"
version = "0.1.0"
authors = ["Howard.Zuo <leftstick@qq.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { workspace = true, features = ["derive"] }
strum.workspace = true
strum_macros.workspace = true
gloo.workspace = true
nanoid = "0.4"
rand.workspace = true
getrandom = { workspace = true }
yew = { path = "../../packages/yew", features = ["csr"] }

[dependencies.web-sys]
workspace = true
features = [
	"HtmlInputElement",
]
