[package]
name = "crm"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1"
serde_derive = "1"
yew = { path = "../.." }
pulldown-cmark = "0.1.2"

[features]
std_web = ["yew/std_web"]
web_sys = ["yew/web_sys"]
