[package]
name = "website-test"
version = "0.1.0"
edition = "2021"
build = "build.rs"
publish = false
rust-version = "1.84.0"

[dependencies]
yew-agent = { path = "../../packages/yew-agent/" }

[dev-dependencies]
derive_more = { version = "2.0", features = ["from"] }
gloo.workspace = true
gloo-net = "0.6"
js-sys.workspace = true
serde = { workspace = true, features = ["derive"] }
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
weblog = "0.3.0"
yew = { path = "../../packages/yew/", features = ["ssr", "csr", "serde"] }
yew-autoprops = "0.4.1"
yew-router = { path = "../../packages/yew-router/" }
tokio = { workspace = true, features = ["rt", "macros"] }

[dev-dependencies.web-sys]
workspace = true
features = [
    "Document",
    "Element",
    "EventTarget",
    "HtmlElement",
    "HtmlInputElement",
    "HtmlSelectElement",
    "DomRect",
]

[build-dependencies]
glob = "0.3"
