[package]
name = "website-test"
version = "0.1.0"
edition = "2021"
build = "build.rs"
publish = false

[dependencies]
yew-agent = { path = "../../packages/yew-agent/" }

[dev-dependencies]
boolinator = "2.4"
derive_more = "0.99"
gloo = "0.8"
js-sys = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
weblog = "0.3.0"
yew = { path = "../../packages/yew/", features = ["ssr", "csr"] }
yew-router = { path = "../../packages/yew-router/" }
tokio = { version = "1.15.0", features = ["rt", "macros"] }

[dev-dependencies.web-sys]
version = "0.3"
features = [
    "Document",
    "Element",
    "EventTarget",
    "HtmlElement",
    "HtmlInputElement",
    "HtmlSelectElement",
    "DomRect",
]

[build-dependencies]
glob = "0.3"
