[package]
name = "website-test"
version = "0.1.0"
edition = "2021"
build = "build.rs"
publish = false
rust-version = "1.78"

[dependencies]
yew-agent = { path = "../../packages/yew-agent/" }

[dev-dependencies]
derive_more = { version = "2.0", features = ["from"] }
gloo = "0.11"
gloo-net = "0.6"
js-sys = "0.3"
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
weblog = "0.3.0"
yew = { path = "../../packages/yew/", features = ["ssr", "csr", "serde"] }
yew-autoprops = "0.4.1"
yew-router = { path = "../../packages/yew-router/" }
tokio = { version = "1.43.1", features = ["rt", "macros"] }

[dev-dependencies.web-sys]
version = "0.3"
features = [
    "Document",
    "Element",
    "EventTarget",
    "HtmlElement",
    "HtmlInputElement",
    "HtmlSelectElement",
    "DomRect",
]

[build-dependencies]
glob = "0.3"
