[package]
name = "event_bus"
version = "0.1.0"
edition = "2018"

[dependencies]
log = "0.4"
web_logger = "0.1"
serde = { version = "1.0", features = ["derive"] }
yew = { path = "../..", features = ["std_web"] }
stdweb = "0.4.20"
