[package]
name = "yew-agent"
version = "0.1.0"
authors = ["Hamza <muhammadhamza1311@gmail.com>"]
edition = "2021"
readme = "../../README.md"
description = "Agents for Yew"
license = "MIT OR Apache-2.0"

[dependencies]
yew = { version = "0.19.3", path = "../yew" }
gloo-worker = "0.1"
