[package]
name = "yew-agent"
version = "0.4.0"
authors = ["Hamza <muhammadhamza1311@gmail.com>"]
repository = "https://github.com/yewstack/yew"
homepage = "https://yew.rs"
documentation = "https://docs.rs/yew/"
edition = "2021"
readme = "../../README.md"
description = "Agents for Yew"
license = "MIT OR Apache-2.0"
rust-version = "1.84.0"

[dependencies]
yew = { version = "0.22.1", path = "../yew" }
wasm-bindgen.workspace = true
js-sys.workspace = true
pinned = "0.1.0"
thiserror.workspace = true
bincode = { workspace = true }
wasm-bindgen-futures.workspace = true
serde = { workspace = true, features = ["derive"] }
futures.workspace = true
yew-agent-macro = { version = "0.3", path = "../yew-agent-macro" }

[dependencies.web-sys]
workspace = true
features = [
    "Blob",
    "BlobPropertyBag",
    "DedicatedWorkerGlobalScope",
    "MessageEvent",
    "Url",
    "Worker",
    "WorkerOptions",
	"WorkerType"
]

[dev-dependencies]
serde = { workspace = true }
