[package]
name = "yew-agent"
version = "0.4.0"
authors = ["Hamza <muhammadhamza1311@gmail.com>"]
repository = "https://github.com/yewstack/yew"
homepage = "https://yew.rs"
documentation = "https://docs.rs/yew/"
edition = "2021"
readme = "../../README.md"
description = "Agents for Yew"
license = "MIT OR Apache-2.0"
rust-version = "1.84.0"

[dependencies]
yew = { version = "0.22.0", path = "../yew" }
wasm-bindgen = "0.2"
js-sys = "0.3"
pinned = "0.1.0"
thiserror = "2.0.18"
bincode = { version = "2.0.0-rc.3", features = ["serde"] }
wasm-bindgen-futures = "0.4"
serde = { version = "1", features = ["derive"] }
futures = "0.3"
yew-agent-macro = { version = "0.3", path = "../yew-agent-macro" }

[dependencies.web-sys]
version = "0.3"
features = [
    "Blob",
    "BlobPropertyBag",
    "DedicatedWorkerGlobalScope",
    "MessageEvent",
    "Url",
    "Worker",
    "WorkerOptions",
	"WorkerType"
]

[dev-dependencies]
serde = "1.0.228"
