[package]
name = "yew-agent"
version = "0.2.0"
authors = ["Hamza <muhammadhamza1311@gmail.com>"]
repository = "https://github.com/yewstack/yew"
homepage = "https://yew.rs"
documentation = "https://docs.rs/yew/"
edition = "2021"
readme = "../../README.md"
description = "Agents for Yew"
license = "MIT OR Apache-2.0"
rust-version = "1.64.0"

[dependencies]
yew = { version = "0.20.0", path = "../yew" }
gloo-worker = { version = "0.3", features = ["futures"] }
wasm-bindgen = "0.2"
serde = { version = "1", features = ["derive"] }
futures = "0.3"
pin-project = "1.0.10"
yew-agent-macro = { version = "0.1", path = "../yew-agent-macro" }

[dev-dependencies]
serde = "1.0.164"
