[package]
name = "build-examples"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
reqwest = { workspace = true, features = ["blocking", "json"] }
regex = "1.12.2"
toml = "0.9.8"
serde = { workspace = true, features = ["derive"] }
