[package]
name = "build-examples"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
reqwest = { version = "0.12.26", features = ["blocking", "json"] }
regex = "1.12.2"
toml = "0.9.10"
serde = { version = "1.0.228", features = ["derive"] }
