[package]
name = "boids"
version = "0.1.0"
authors = ["motoki saito <stmtk13044032@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
anyhow.workspace = true
getrandom = { workspace = true }
rand.workspace = true
serde = { workspace = true, features = ["derive"] }
yew = { path = "../../packages/yew", features = ["csr"] }
gloo.workspace = true

[dependencies.web-sys]
workspace = true
features = [
	"HtmlInputElement",
]
