[package]
name = "webgl_std_web"
version = "0.1.0"
authors = ["MikloÌs Tusz <mdtusz@gmail.com>"]
edition = "2018"

[dependencies]
stdweb = "0.4.20"
yew = { path = "../../..", features = [ "std_web" ] }
webgl_stdweb = "0.3.0"
