[package]
name = "yew"
version = "0.22.0"
edition = "2021"
authors = [
  "Denis Kolodin <deniskolodin@gmail.com>",
  "Justin Starry <justin@yew.rs>",
]
repository = "https://github.com/yewstack/yew"
homepage = "https://yew.rs"
documentation = "https://docs.rs/yew/"
license = "MIT OR Apache-2.0"
keywords = ["web", "webasm", "javascript"]
categories = ["gui", "wasm", "web-programming"]
description = "A framework for creating reliable and efficient web applications"
readme = "../../README.md"
rust-version = "1.84.0"

[dependencies]
console_error_panic_hook = "0.1"
gloo.workspace = true
indexmap = { version = "2.13", features = ["std"] }
js-sys.workspace = true
slab = "0.4"
wasm-bindgen.workspace = true
yew-macro = { version = "^0.22.0", path = "../yew-macro" }
thiserror.workspace = true
futures = { workspace = true, default-features = false, features = ["std"] }
html-escape = { version = "0.2.13", optional = true }
implicit-clone = { workspace = true, features = ["map"] }
base64ct = { version = "1.6.0", features = ["std"], optional = true }
bincode = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
tracing = "0.1.44"
tokise = "0.2.0"
rustversion.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# We still need tokio as we have docs linked to it.
tokio = { workspace = true, features = ["rt"] }

[dependencies.web-sys]
workspace = true
features = [
  "AnimationEvent",
  "Document",
  "DragEvent",
  "Element",
  "ErrorEvent",
  "Event",
  "EventInit",
  "EventTarget",
  "FocusEvent",
  "HtmlElement",
  "HtmlInputElement",
  "HtmlCollection",
  "HtmlTextAreaElement",
  "InputEvent",
  "InputEventInit",
  "KeyboardEvent",
  "Location",
  "MouseEvent",
  "Node",
  "NodeList",
  "PointerEvent",
  "ProgressEvent",
  "ShadowRoot",
  "Text",
  "TouchEvent",
  "TransitionEvent",
  "UiEvent",
  "WheelEvent",
  "Window",
  "HtmlScriptElement",
  "SubmitEvent",
]

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }

[target.'cfg(all(target_arch = "wasm32", target_os = "wasi"))'.dependencies]
tokio = { workspace = true, features = ["macros", "rt", "time"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"
gloo = { workspace = true, features = ["futures"] }
wasm-bindgen-futures.workspace = true
trybuild = { workspace = true }

[dev-dependencies.web-sys]
workspace = true
features = ["ShadowRootInit", "ShadowRootMode", "HtmlButtonElement"]

[features]
ssr = ["dep:html-escape", "dep:base64ct", "dep:bincode"]
csr = []
hydration = ["csr", "dep:bincode"]
not_browser_env = []
default = []
test = []
serde = ["implicit-clone/serde"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "documenting"]

[lints]
workspace = true
