[package]
name = "yew"
version = "0.19.3"
edition = "2021"
authors = [
  "Denis Kolodin <deniskolodin@gmail.com>",
  "Justin Starry <justin@yew.rs>",
]
repository = "https://github.com/yewstack/yew"
homepage = "https://github.com/yewstack/yew"
documentation = "https://docs.rs/yew/"
license = "MIT OR Apache-2.0"
keywords = ["web", "webasm", "javascript"]
categories = ["gui", "wasm", "web-programming"]
description = "A framework for making client-side single-page apps"
readme = "../../README.md"
rust-version = "1.60.0"

[dependencies]
console_error_panic_hook = "0.1"
gloo = "0.8"
indexmap = { version = "1", features = ["std"] }
js-sys = "0.3"
slab = "0.4"
wasm-bindgen = "0.2"
yew-macro = { version = "^0.19.0", path = "../yew-macro" }
thiserror = "1.0"
futures = { version = "0.3", default-features = false, features = ["std", "async-await"] }
html-escape = { version = "0.2.9", optional = true }
implicit-clone = { version = "0.3", features = ["map"] }
base64ct = { version = "1.5.0", features = ["std"], optional = true }
bincode = { version = "1.3.3", optional = true }
serde = { version = "1", features = ["derive"] }
tracing = "0.1.36"
pin-project = "1.0.11"

[dependencies.web-sys]
version = "^0.3.59"
features = [
  "AnimationEvent",
  "Document",
  "DragEvent",
  "Element",
  "ErrorEvent",
  "Event",
  "EventInit",
  "EventTarget",
  "FocusEvent",
  "HtmlElement",
  "HtmlInputElement",
  "HtmlTextAreaElement",
  "InputEvent",
  "InputEventInit",
  "KeyboardEvent",
  "Location",
  "MouseEvent",
  "Node",
  "NodeList",
  "PointerEvent",
  "ProgressEvent",
  "ShadowRoot",
  "Text",
  "TouchEvent",
  "TransitionEvent",
  "UiEvent",
  "WheelEvent",
  "Window",
  "HtmlScriptElement",
  "SubmitEvent"
]

[target.'cfg(target_arch = "wasm32")'.dependencies]
# we move it here so no promise-based spawn_local can present for
# non-wasm32 targets.
wasm-bindgen-futures = "0.4"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
num_cpus = { version = "1.13", optional = true }
once_cell = "1"
tokio = { version = "1.21.1", features = ["rt", "time"], optional = true }
tokio-stream = { version = "0.1", features = ["time"], optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"
gloo = { version = "0.8", features = ["futures"] }
wasm-bindgen-futures = "0.4"
rustversion = "1"
trybuild = "1"

[dev-dependencies.web-sys]
version = "0.3"
features = [
  "ShadowRootInit",
  "ShadowRootMode",
]

[features]
tokio = ["dep:tokio", "dep:num_cpus", "dep:tokio-stream"]
ssr = ["dep:html-escape", "dep:base64ct", "dep:bincode"]
csr = []
hydration = ["csr", "dep:bincode"]
default = []

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { version = "1.19", features = ["full"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "documenting"]
