[tasks.native-test]
command = "cargo"
args = ["test", "--features", "csr,ssr,hydration"]

[tasks.wasm-test]
command = "wasm-pack"
args = [
    "test",
    "--firefox",
    "--headless",
    "--",
    "--features",
    "csr,hydration,ssr",
]

[tasks.ssr-test]
command = "cargo"
args = ["test", "ssr_tests", "--features", "ssr"]

[tasks.test]
args = ["test", "--all-targets", "--all-features"]
dependencies = ["native-test", "wasm-test"]

[tasks.clippy-feature-soundness]
command = "cargo"
args = [
    "hack", "clippy",
    "-p", "yew", "-p", "yew-agent", "-p", "yew-router",
    "--feature-powerset", "--no-dev-deps",
    "--exclude-features", "test,serde,not_browser_env",
    "--keep-going",
    "--", "-D", "warnings",
]
