[package]
name = "yew-router-route-parser"
version = "0.14.0"
authors = ["Henry Zimmerman <zimhen7@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "The parser for the routing syntax used with yew-router"
repository = "https://github.com/yewstack/yew"

[dependencies]
nom = "6.0.1"
