[package]
name = "showcase"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>", "Limira"]
edition = "2018"

[dependencies]
log = "0.4"
web_logger = "0.1"
strum = "0.13"
strum_macros = "0.13"
yew = { path = "../.." }
counter = { path = "../counter" }
crm = { path = "../crm" }
custom_components = { path = "../custom_components" }
dashboard = { path = "../dashboard" }
node_refs = { path = "../node_refs" }
fragments = { path = "../fragments" }
game_of_life = { path = "../game_of_life" }
inner_html = { path = "../inner_html" }
large_table = { path = "../large_table" }
mount_point = { path = "../mount_point" }
npm_and_rest = { path = "../npm_and_rest" }
textarea = { path = "../textarea" }
timer = { path = "../timer" }
todomvc = { path = "../todomvc" }
two_apps = { path = "../two_apps" }
