[package]
name = "common"
version = "0.1.0"
authors = ["Martin Matusiak <numerodix@gmail.com>"]
edition = "2018"
description="A useful utility for handing markdown which is used by other examples â€“ not an example in itself!"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pulldown-cmark = { version = "0.7.0", default-features = false }
wasm-bindgen = "0.2.64"
yew = { path = "../../yew" }
