[package]
name = "password_strength"
version = "0.1.0"
authors = ["Philip Peterson <pc.peterso@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
yew = { path = "../../packages/yew", features = ["csr"] }
zxcvbn = "3.1.0"
time = "0.3.44"
js-sys.workspace = true
web-sys = { workspace = true, features = ["Event","EventTarget","InputEvent"] }
wasm-bindgen.workspace = true
chrono = { workspace = true, features = ["wasmbind"] }
