[package]
name = "yew-worker-prime"
version = "0.1.0"
edition = "2021"

[dependencies]
yew-agent = { path = "../../packages/yew-agent" }
yew = { path = "../../packages/yew", features = ["csr"] }
futures = "0.3.30"
primes = "0.3.0"
serde = { version = "1.0.197", features = ["derive"] }
