[package]
name = "yew-worker-prime"
version = "0.1.0"
edition = "2021"

[dependencies]
yew-agent = { path = "../../packages/yew-agent" }
yew = { path = "../../packages/yew", features = ["csr"] }
futures.workspace = true
primes = "0.4.0"
serde = { workspace = true, features = ["derive"] }
