[package]
name = "suspense"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { path = "../../packages/yew", features = ["csr"] }
gloo = { workspace = true, features = ["futures"] }
wasm-bindgen-futures.workspace = true
wasm-bindgen.workspace = true

[dependencies.web-sys]
workspace = true
features = [
    "HtmlTextAreaElement",
]
