[package]
name = "suspense"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { path = "../../packages/yew", features = ["csr"] }
gloo = { version = "0.10", features = ["futures"] }
wasm-bindgen-futures = "0.4"
wasm-bindgen = "0.2"

[dependencies.web-sys]
version = "0.3"
features = [
    "HtmlTextAreaElement",
]
