[package]
name = "keyed_list"
version = "0.1.0"
authors = ["Thomas Lacroix <toto.rigolo@free.fr>"]
edition = "2018"

[dependencies]
log = "0.4"
instant = { version = "0.1", features = ["wasm-bindgen"] }
rand = { version = "0.7", features = ["wasm-bindgen"] }
wasm-logger = "0.2"
yew = { path = "../../yew" }
yewtil = { path = "../../yewtil" }
fake = "2.2"
