[package]
name = "keyed_list"
version = "0.1.0"
authors = ["Thomas Lacroix <toto.rigolo@free.fr>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
fake = "4.0.0"
getrandom = { workspace = true }
instant = { workspace = true }
log.workspace = true
rand.workspace = true
wasm-logger.workspace = true
yew = { path = "../../packages/yew", features = ["csr"] }

[dependencies.web-sys]
workspace = true
features = [
    "HtmlElement",
    "HtmlInputElement",
]
