[package]
name = "yew-agent-macro"
version = "0.3.0"
edition = "2021"
rust-version = "1.84.0"
authors = ["Kaede Hoshikawa <futursolo@icloud.com>"]
repository = "https://github.com/yewstack/yew"
homepage = "https://yew.rs"
documentation = "https://docs.rs/yew/"
readme = "../../README.md"
description = "Macro Support for Yew Agents"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn = { workspace = true, features = ["full", "extra-traits"] }

[dev-dependencies]
rustversion = "1"
trybuild = { workspace = true }
yew-agent = { path = "../yew-agent" }
