[package]
name = "router"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
instant = { workspace = true }
lipsum = { version = "0.9.1", git = "https://github.com/mgeisler/lipsum.git", branch = "master" }
log.workspace = true
getrandom = { workspace = true }
rand = { workspace = true, features = ["small_rng"] }
wasm-logger.workspace = true
yew = { path = "../../packages/yew", features = ["csr"] }
yew-router = { path = "../../packages/yew-router" }
serde = { workspace = true, features = ["derive"] }
once_cell.workspace = true
gloo.workspace = true
