[package]
name = "wasi_ssr_module"
version = "0.1.0"
edition = "2021"
authors = ["langyo <langyo.china@gmail.com>"]

[dependencies]
yew = { path = "../../packages/yew", features = ["ssr"] }
yew-router = { path = "../../packages/yew-router" }

anyhow = "^1"
bytes = { workspace = true }
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
lazy_static = "^1"

tokio = { workspace = true, features = ["macros", "rt", "time"] }
