[package]
name = "nested_list"
version = "0.1.0"
authors = ["Justin Starry <justin.starry@icloud.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
implicit-clone = { workspace = true }
log.workspace = true
wasm-logger.workspace = true
yew = { path = "../../packages/yew", features = ["csr"] }
