[package]
name = "nested_list"
version = "0.1.0"
authors = ["Justin Starry <justin.starry@icloud.com>"]
edition = "2018"

[dependencies]
log = "0.4"
web_logger = "0.2"
yew = { path = "../../yew" }

[features]
std_web = ["yew/std_web"]
web_sys = ["yew/web_sys"]

[lib]
crate-type = ["cdylib", "rlib"]
