[package]
name = "changelog"
version = "0.1.0"
authors = ["Cecile Tonglet <cecile.tonglet@cecton.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
chrono = "0.4"
git2 = "0.20"
regex = "1"
reqwest = { workspace = true, features = ["blocking", "json"] }
serde = { workspace = true, features = ["derive"] }
strum = { workspace = true, features = ["derive"] }
clap = { workspace = true }
semver = "1.0"
once_cell.workspace = true
