[package]
name = "yew-macro"
version = "0.19.3"
edition = "2018"
authors = ["Justin Starry <justin@yew.rs>"]
repository = "https://github.com/yewstack/yew"
homepage = "https://github.com/yewstack/yew"
documentation = "https://docs.rs/yew-macro/"
license = "MIT OR Apache-2.0"
keywords = ["web", "wasm", "frontend", "webasm", "webassembly"]
categories = ["gui", "web-programming", "wasm"]
description = "A framework for making client-side single-page apps"

[lib]
proc-macro = true

[dependencies]
boolinator = "2"
lazy_static = "1"
proc-macro-error = "1"
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full", "extra-traits"] }

# testing
[dev-dependencies]
rustversion = "1"
trybuild = "1"
yew = { path = "../yew" }

[build-dependencies]

[features]
doc_test = []
lints = []
