[tasks.test]
clear = true
toolchain = "1.64.0"
command = "cargo"
# test target can be optionally specified like `cargo make test html_macro`,
args = ["test", "${@}"]

[tasks.test-lint]
clear = true
toolchain = "nightly"
command = "cargo"
args = ["test", "test_html_lints", "--features", "lints"]

[tasks.test-overwrite]
extend = "test"
env = { TRYBUILD = "overwrite" }
