[package]
name = "mount_point"
version = "0.1.0"
authors = ["Ben Berman <ben@standardbots.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
wasm-bindgen.workspace = true
yew = { path = "../../packages/yew", features = ["csr"] }
gloo.workspace = true

[dependencies.web-sys]
workspace = true
features = [
  "CanvasRenderingContext2d",
  "Document",
  "DomTokenList",
  "Element",
  "HtmlCanvasElement",
  "Node",
  "Window"
]
