[package]
name = "immutable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
implicit-clone = { workspace = true, features = ["map"] }
wasm-bindgen.workspace = true
web-sys.workspace = true
yew = { path = "../../packages/yew", features = ["csr"] }
