[package]
name = "ssr_router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ssr_router_hydrate"
required-features = ["hydration"]

[[bin]]
name = "ssr_router_server"
required-features = ["ssr"]

[dependencies]
yew = { path = "../../packages/yew" }
function_router = { path = "../function_router" }
log = "0.4"
futures = { version = "0.3", features = ["std"], default-features = false }
hyper-util = "0.1.11"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"
wasm-logger = "0.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.44.2", features = ["full"] }
axum = "0.8"
tower = { version = "0.5", features = ["make"] }
tower-http = { version = "0.6", features = ["fs"] }
env_logger = "0.11"
clap = { version = "4", features = ["derive"] }
hyper = { version = "1.4", features = ["server", "http1"] }

[target.'cfg(unix)'.dependencies]
jemallocator = "0.5"

[features]
ssr = ["yew/ssr"]
hydration = ["yew/hydration"]
