[package]
name = "dyn_create_destroy_apps"
version = "0.1.0"
authors = ["Nicklas Warming Jacobsen <nicklaswj@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
js-sys.workspace = true
yew = { path = "../../packages/yew", features = ["csr"] }
slab = "0.4.9"
gloo.workspace = true
wasm-bindgen.workspace = true

[dependencies.web-sys]
workspace = true
features = [
    "Document",
    "Element",
    "Node",
    "DomTokenList"
]
