[package]
name = "dyn_create_destroy_apps"
version = "0.1.0"
authors = ["Nicklas Warming Jacobsen <nicklaswj@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
js-sys = "0.3"
yew = { path = "../../packages/yew" }
slab = "0.4.3"
gloo = "0.4"
wasm-bindgen = "0.2"
gloo-utils = "0.1"

[dependencies.web-sys]
version = "0.3.50"
features = [
    "Document",
    "Element",
    "Node",
    "DomTokenList"
]
