[package]
name = "file_upload"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
edition = "2018"

[dependencies]
js-sys = "0.3"
yew = { path = "../../yew" }
yew-services = { path = "../../yew-services" }
