[package]
name = "futures"
version = "0.1.0"
authors = ["Henry Zimmerman <zimhen7@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
pulldown-cmark = { version = "0.13", default-features = false }
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
yew = { path = "../../packages/yew", features = ["csr"] }
gloo.workspace = true

[dependencies.web-sys]
workspace = true
features = [
  "Headers",
  "Request",
  "RequestInit",
  "RequestMode",
  "Response",
  "Window",
]
