[package]
name = "inner_html_std_web"
version = "0.1.0"
authors = ["Garrett Berg <vitiral@gmail.com>"]
edition = "2018"

[dependencies]
stdweb = "0.4.20"
yew = { path = "../../..", features = ["std_web"] }

[target.'cfg(all(target_arch = "wasm32", not(target_os="wasi"), not(cargo_web)))'.dependencies]
wasm-bindgen = "0.2.60"
