[package]
name = "pure_component"
version = "0.1.0"
authors = ["Henry Zimmerman <zimhen7@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
log = "0.4.8"
web_logger = "0.2.0"
yew = { path = "../../../yew" }
yewtil = { path = "../.." }
