[package]
name = "store"
version = "0.1.0"
authors = ["Micha≈Ç Kawalec <michal@monad.cat>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
yew = { path = "../../packages/yew" }
yew-agent = { path = "../../packages/yew-agent" }
yewtil = { path = "../../packages/yewtil" }
weblog = "0.3"
wasm-bindgen = "0.2"
