[package]
name = "simple_ssr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "simple_ssr_hydrate"
required-features = ["hydration"]

[[bin]]
name = "simple_ssr_server"
required-features = ["ssr"]

[dependencies]
yew = { path = "../../packages/yew" }
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
uuid = { version = "1.18.1", features = ["serde"] }
futures.workspace = true
bytes = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures.workspace = true
wasm-logger.workspace = true
log.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "fs"] }
warp = "0.3"
clap = { workspace = true }

[features]
hydration = ["yew/hydration"]
ssr = ["yew/ssr"]
