[package]
name = "yew-worker-fib"
version = "0.1.0"
edition = "2021"
authors = ["Shrey Somaiya", "Zac Kologlu"]

[dependencies]
yew = { path = "../../packages/yew", features = ["csr"] }
yew-agent = { path = "../../packages/yew-agent" }
wasm-bindgen.workspace = true
js-sys.workspace = true
web-sys = { workspace = true, features = [ "HtmlInputElement" ] }
serde = { workspace = true, features = ["derive"] }
postcard = "1.0.10"
