[package]
name = "js_callback"
version = "0.1.0"
authors = ["Scott Steele <scottlsteele@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
wasm-bindgen = "0.2"
yew = { path = "../../packages/yew" }

[dependencies.web-sys]
version = "0.3"
features = [
	"HtmlTextAreaElement",
]
