[package]
name = "js_callback"
version = "0.1.0"
authors = ["Scott Steele <scottlsteele@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
wasm-bindgen.workspace = true
yew = { path = "../../packages/yew", features = ["csr"] }
wasm-bindgen-futures.workspace = true
js-sys.workspace = true
once_cell.workspace = true
