[package]
name = "function_router"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
lipsum = { version = "0.9.1", git = "https://github.com/mgeisler/lipsum.git", branch = "master" }
log.workspace = true
rand = { workspace = true, features = ["small_rng"] }
yew = { path = "../../packages/yew" }
yew-router = { path = "../../packages/yew-router" }
serde = { workspace = true, features = ["derive"] }
gloo.workspace = true
wasm-logger.workspace = true
instant = { workspace = true }
once_cell.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { workspace = true }

[[bin]]
name = "function_router"
required-features = ["yew/csr"]
