[package]
name = "devtools-extension"
version = "0.1.0"
authors = ["Yew Mainainers <mainainers@yew.rs>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
