[package]
name = "function_todomvc"
version = "0.1.0"
authors = ["Drew Hutton <drew.hutton@pm.me>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { workspace = true, features = ["derive"] }
strum.workspace = true
strum_macros.workspace = true
gloo.workspace = true
yew = { path = "../../packages/yew", features = ["csr"] }

[dependencies.web-sys]
workspace = true
features = [
	"HtmlInputElement",
]
