[package]
name = "yew-test-runner"
version = "0.19.0"
edition = "2021"
authors = [
  "Martin Molzer <WorldSEnder@users.noreply.github.com>",
]
repository = "https://github.com/yewstack/yew"
homepage = "https://github.com/yewstack/yew"
documentation = "https://docs.rs/yew/"
license = "MIT OR Apache-2.0"
keywords = ["web", "webasm", "javascript"]
categories = ["gui", "wasm", "web-programming"]
description = "A framework for testing client-side single-page apps"
readme = "./README.md"
rust-version = "1.60.0"

[dependencies]
gloo = "0.8"
tracing = "0.1.36"
yew = { version = "0.19", path = "../yew", features = ["csr"] }

[dependencies.web-sys]
version = "^0.3.59"

[dev-dependencies]
wasm-bindgen-test = "0.3"

[features]
default = ["hydration"]
hydration = ["yew/ssr", "yew/hydration"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "documenting"]
