[package]
name = "benchmark-ssr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { path = "../../packages/yew", features = ["ssr"] }
function_router = { path = "../../examples/function_router" }
tokio = { version = "1.37", features = ["full"] }
average = "0.15.1"
tabled = "0.15.0"
indicatif = "0.17.8"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.109"
clap = { version = "4", features = ["derive"] }

[target.'cfg(unix)'.dependencies]
jemallocator = "0.5.4"
