[package]
name = "benchmark-ssr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { path = "../../packages/yew", features = ["ssr"] }
function_router = { path = "../../examples/function_router" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
average = "0.16.0"
tabled = "0.20.0"
indicatif = "0.18.4"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
clap = { workspace = true }

[target.'cfg(unix)'.dependencies]
jemallocator = "0.5.4"
