[package]
name = "benchmark-ssr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { path = "../../packages/yew", features = ["ssr"] }
function_router = { path = "../../examples/function_router" }
tokio = { version = "1.26", features = ["full"] }
jemallocator = "0.5.0"
average = "0.13.1"
tabled = "0.8.0"
indicatif = "0.17.0"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.82"
clap = { version = "3.2.8", features = ["derive"] }
