name: Publish yew-agent
permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      level:
        description: "Version Level major|minor|patch"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
jobs:
  publish:
    name: Publish yew-agent
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          token: "${{ secrets.YEWTEMPBOT_TOKEN }}"
          fetch-depth: 0

      - name: Config Git
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: "${{ secrets.YEWTEMPBOT_TOKEN }}"

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Install cargo binary dependencies
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-release
          version: 0.18.5

      - name: Build changelog generator
        run: cargo build --release -p changelog

      - name: Generate changelog
        uses: mathiasvr/command-output@v1
        id: changelog
        with:
          run: ./target/release/changelog yew-agent ${{ github.event.inputs.level }}

      - name: Commit changelog
        run: |
          git add CHANGELOG.md
          git commit -m "update CHANGELOG.md for yew-agent release"
          git push origin master

      - name: Release yew-agent
        run: cargo release ${PUBLISH_LEVEL} --token ${CRATES_TOKEN} --execute --no-confirm --package yew-agent
        env:
          PUBLISH_LEVEL: ${{ github.event.inputs.level }}
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

      - name: Get tag
        id: gettag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Create a version branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ steps.gettag.outputs.tag }}

      - name: Create a Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.YEWTEMPBOT_TOKEN }}
          tag_name: ${{ steps.gettag.outputs.tag }}
          body: ${{ steps.changelog.outputs.stdout }}
