name: Publish Examples
on:
  push:
    branches: [master]
    paths-ignore:
      - "**/*.md"
      - "website/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      # leave empty for /
      PUBLIC_URL_PREFIX: ""

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

      - uses: Swatinem/rust-cache@v1

      - uses: jetli/trunk-action@v0.1.0
        with:
          # Optional version of trunk to install(eg. 'v0.8.1', 'latest')
          version: 'latest'



      - name: Build examples
        run: |
          output="$(pwd)/dist"
          mkdir "$output"

          for path in examples/*; do
            if [[ ! -d $path ]]; then
              continue
            fi

            example=$(basename "$path")

            # multi_thread doesn't work yet. See <https://github.com/thedodd/trunk/issues/40>.
            if [[ "$example" == "agents" ]]; then
              continue
            fi

            # web_worker_fib does not compile with trunk. See <https://github.com/thedodd/trunk/issues/46>.
            if [[ "$example" == "web_worker_fib" ]]; then
              continue
            fi

            echo "building: $example"
            (
              cd "$path"
              dist_dir="$output/$example"

              trunk build --release --dist "$dist_dir" --public-url "$PUBLIC_URL_PREFIX/$example"
            )
          done



      - name: Deploy to Firebase
        uses: siku2/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseToken: "${{ secrets.FIREBASE_TOKEN }}"
          channelId: live
          targets: examples
