name: Publish Examples
on:
  push:
    branches: [master]
    paths:
      - 'tools/build-examples/**'
      - 'examples/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      # leave empty for /
      PUBLIC_URL_PREFIX: ""
      RUSTUP_TOOLCHAIN: nightly

    steps:
      - uses: actions/checkout@v6

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          targets: wasm32-unknown-unknown
          components: rust-src

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: publish-examples

      - uses: jetli/trunk-action@v0.5.1
        with:
          version: 'latest'

      - name: Get latest wasm-opt version
        id: wasm-opt
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: WebAssembly/binaryen
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build examples
        run: cargo run -p build-examples --bin build-examples
        env:
          LATEST_WASM_OPT_VERSION: ${{ steps.wasm-opt.outputs.release }}

      - name: Deploy to Firebase
        uses: siku2/action-hosting-deploy@v1
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseToken: "${{ secrets.FIREBASE_TOKEN }}"
          channelId: live
          targets: examples
